### ISSUE TITLE
Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.le.ScanResult.getDevice()' on a null object reference

### ISSUE THREAD

**Issue by wzh469649067** [RianOvO/esp_blufi#2]
try {
      await _espBlufiPlugin.scanDeviceInfo(filterString: "F8:B3:B7:47:5D:8A");
      var duration = const Duration(seconds: 30);
      print('Start sleeping');
      sleep(duration);
      print('30 seconds has passed');
      //_espBlufiPlugin.stopScan();
      await _espBlufiPlugin.connectPeripheral(
          peripheralAddress: "F8:B3:B7:47:5D:8A");
    } on PlatformException catch (e) {
      print('Failed to scan or connect to peripheral: $e');
    }
E/MethodChannel#esp_blufi(21654): Failed to handle method call
E/MethodChannel#esp_blufi(21654): java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.le.ScanResult.getDevice()' on a null object reference
E/MethodChannel#esp_blufi(21654):       at yu.legend.esp_blufi.EspBlufiPlugin.onMethodCall(EspBlufiPlugin.java:160)
E/MethodChannel#esp_blufi(21654):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#esp_blufi(21654):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#esp_blufi(21654):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#esp_blufi(21654):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#esp_blufi(21654):       at android.os.Handler.handleCallback(Handler.java:790)
E/MethodChannel#esp_blufi(21654):       at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#esp_blufi(21654):       at android.os.Looper.loop(Looper.java:164)
E/MethodChannel#esp_blufi(21654):       at android.app.ActivityThread.main(ActivityThread.java:6581)
E/MethodChannel#esp_blufi(21654):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#esp_blufi(21654):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#esp_blufi(21654):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by RianOvO** [comment]
filterString should not be a MAC Address, otherwise the device will not be included in the searched device list and you will not be able to connect to the device.

```java
if (call.method.equals("connectPeripheral")) {
    String deviceId = call.argument("peripheral");
    if (deviceId != null) {
      connectDevice(mDeviceMap.get(deviceId).getDevice());
      result.success(true);
    } else {
      result.success(false);
    }
  }
```

**Comment by wzh469649067** [comment]
Is there a complete sample program? I would appreciate it if you could provide that

**Comment by RianOvO** [comment]
```java
class DiscoverDevicesController extends GetxController {
  final isBleEnable = true.obs;
  Map<String, dynamic> scanResult = <String, dynamic>{};
  final discoveredDeviceIds = <String>[].obs;
  final discoveredDevices = <DiscoverDevice>[].obs;

  final selectedAddress = "".obs;

  Timer? _timer;
  int _countdownTime = -1; 
  final searchTimeout = false.obs;

  final isSearching = false.obs;

  void startCountdownTimer() {
    callback(timer) {
      listenerBleState();

      if (_countdownTime == 0) {
        searchTimeout.value = true;
      } else {
        _countdownTime = _countdownTime - 1;
      }
    }

    _timer = Timer.periodic(const Duration(seconds: 1), callback);
  }

  Future<void> checkBlePermissions() async {
    var isBleGrantedStatus = false;
    if (Platform.isIOS) {
      var isBleGranted = await Permission.bluetooth.request();
      Logger().d(isBleGranted);
      isBleGrantedStatus = isBleGranted == PermissionStatus.granted;
    } else {
      var isLocationGranted = await Permission.locationWhenInUse.request();

      var isBleScanGranted = await Permission.bluetoothScan.request();

      var isBleConnectGranted = await Permission.bluetoothConnect.request();
      isBleGrantedStatus = isLocationGranted == PermissionStatus.granted &&
          isBleScanGranted == PermissionStatus.granted &&
          isBleConnectGranted == PermissionStatus.granted;
    }
    if (!isBleGrantedStatus) {
      showBlePermissionSheet();
    }

    startCountdownTimer();
  }

  void showBlePermissionSheet() {
    final localizations = AppLocalizations.of(Get.context!)!;
    Get.bottomSheet(
        isScrollControlled: true,
        backgroundColor: Theme.of(Get.context!).colorScheme.dialogBg(),
        shape: const RoundedRectangleBorder(
            borderRadius: BorderRadius.only(
          topRight: Radius.circular(8),
          topLeft: Radius.circular(8),
        )),
        Padding(
          padding: EdgeInsets.only(
              top: 30, left: 16, right: 16, bottom: pagePaddingBottom),
          child: Wrap(
            children: [
              Column(
                children: [
                  Image.asset(
                    Assets.imagesLogo,
                    width: 85,
                    height: 40,
                    color: Theme.of(Get.context!).colorScheme.textPrimary(),
                  ),
                  const SizedBox(
                    height: 40,
                  ),
                  Text(
                    localizations.requestBlePermissionTips,
                    style: Theme.of(Get.context!)
                        .textTheme
                        .dinMedium13(Get.context!),
                  ),
                  const SizedBox(
                    height: 40,
                  ),
                  Row(
                    children: [
                      Expanded(
                          child: SecondaryButton(
                              btnText: localizations.cancel,
                              onPressed: () {
                                Get.offAllNamed(Routes.MAIN);
                              })),
                      const SizedBox(
                        width: 11,
                      ),
                      Expanded(
                          child: PrimaryButton(
                        btnText: localizations.next,
                        onPressed: () async {
                          Get.close();
                          requestBlePermissions();
                        },
                      ))
                    ],
                  ),
                ],
              )
            ],
          ),
        ));
  }

  Future<void> listenerBleState() async {
    var isEnable = await Permission.bluetooth.serviceStatus.isEnabled;
    isBleEnable.value = isEnable;
    if (isEnable) {
      scanForBleDevices();
    } else {
      stopScan();
    }
  }

  Future<void> requestBlePermissions() async {
    var status = await Permission.bluetooth.status;
    Logger().d("status=$status");
    if (status == PermissionStatus.denied) {
      if (Platform.isIOS) {
        var isBleGranted = await Permission.bluetooth.request();
        Get.printInfo(info: 'checkBlePermissions, isBleGranted=$isBleGranted');
        Logger().d(isBleGranted);
        if (isBleGranted != PermissionStatus.granted) {
          openAppSettings();
        } else {
          scanForBleDevices();
        }
      } else {
        location.Location l = location.Location();
        bool serviceEnabled;

        serviceEnabled = await l.serviceEnabled();
        if (!serviceEnabled) {
          serviceEnabled = await l.requestService();
          if (!serviceEnabled) {
            Get.back();
          }
        }
        var isLocationGranted = await Permission.locationWhenInUse.request();
        Get.printInfo(
            info: 'checkBlePermissions, isLocationGranted=$isLocationGranted');

        var isBleScanGranted = await Permission.bluetoothScan.request();
        Get.printInfo(
            info: 'checkBlePermissions, isBleScanGranted=$isBleScanGranted');

        var isBleConnectGranted = await Permission.bluetoothConnect.request();
        Get.printInfo(
            info:
                'checkBlePermissions, isBleConnectGranted=$isBleConnectGranted');

        if (isLocationGranted != PermissionStatus.granted &&
            isBleScanGranted != PermissionStatus.granted &&
            isBleConnectGranted != PermissionStatus.granted) {
          Get.back();
          if (isLocationGranted == PermissionStatus.permanentlyDenied ||
              isLocationGranted == PermissionStatus.permanentlyDenied ||
              isBleConnectGranted == PermissionStatus.permanentlyDenied) {
            openAppSettings();
          }
        } else {
          scanForBleDevices();
        }
      }
    } else {
      openAppSettings();
    }
  }

  @override
  void onInit() {
    checkBlePermissions();
    EspBlufi.instance.onMessageReceived(successCallback: (String? data) {
      if (data != null) {
        try {
          Map<String, dynamic> mapData = json.decode(data);

          if (mapData.containsKey('key')) {
            String key = mapData['key'];
            if (key == 'ble_scan_result') {
              _countdownTime = -1;
              Map<String, dynamic> peripheral = mapData['value'];

              String address = peripheral['address'];
              String name = peripheral['name'];
              String rssi = peripheral['rssi'];
              DiscoverDevice device =
                  DiscoverDevice(address: address, name: name, rssi: rssi);

              scanResult[address] = name;
              if (!discoveredDeviceIds.contains(address)) {
                discoveredDeviceIds.add(address);
                discoveredDevices.add(device);
              }
            }
          }
        } on FormatException catch (e) {
          Get.printInfo(info: 'there is a format exception: ${e.message}');
        } catch (e) {
          Get.printInfo(info: 'something went wrong: ${e.toString()}');
        }
        // });
      }
    }, errorCallback: (String? error) {
      if (error != null) {}
      Get.printInfo(info: 'there is some error:  ${error!.toString()}');
    });
    super.onInit();
  }

  Future<void> scanForBleDevices() async {
    Logger().d("scanForBleDevices");
    if (isSearching.value) return;
    _countdownTime = 30;
    Get.printInfo(info: 'running scan for devices from flutter app....');
    // await FlutterBlufi.instance.requestCloseConnection();
    isSearching.value = true;
    discoveredDeviceIds.value = []; // reset the list
    discoveredDevices.value = [];
    // isScanning = true;
    await EspBlufi.instance.scanDeviceInfo(filterString: "xxxx");
  }

  Future<void> stopScan() async {
    Get.printInfo(info: 'stop scan for devices from flutter app....');
    // await FlutterBlufi.instance.requestCloseConnection();
    _countdownTime = -1;
    await EspBlufi.instance.stopScan();

    isSearching.value = false;
    discoveredDeviceIds.value = []; // reset the list
    discoveredDevices.value = [];
  }

  @override
  void onClose() {
    _timer?.cancel();
    stopScan();
    super.onClose();
  }
}

```

**Comment by wzh469649067** [comment]
Can I provide the complete source code? wechat:wzh469649067 or mail box wzh3280@126.com  It can also be offered for a fee
